/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.zapateria.gui;

import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import org.zapateria.logica.Rol;
import org.zapateria.logica.Usuario;
import org.zapateria.utilidades.Constantes;

/**
 *
 * @author geiner
 */
public class RolAdministradorGUI extends javax.swing.JFrame {
    
    private Usuario usuario;
    /**
     * Creates new form rolGUI
     */
    public RolAdministradorGUI() {
        this.usuario = (Usuario)Constantes.session.get(Constantes.USUARIO);
        initComponents();
    }

    public RolAdministradorGUI(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cambiarRol = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();
        comboAdministrador = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zapateria");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Seleccione su rol");

        cambiarRol.setText("Cambiar Rol");
        cambiarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarRolActionPerformed(evt);
            }
        });

        cerrarSesion.setText("Cerrar sesión");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });

		addComboAdmin();
		
        comboAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAdministradorActionPerformed(evt);
            }
        });

        jLabel2.setText("Bienvenido a Zapateria (Administrador)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(cambiarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cambiarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cambiarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarRolActionPerformed
          
        if (this.comboAdministrador.getSelectedItem().equals(Constantes.CLIENTE_ROL)) {
            ClienteGUI clienteGUI = new ClienteGUI();
            clienteGUI.setVisible(true);
            this.dispose();
            System.out.println(this.comboAdministrador.getSelectedItem());
        }
        if (this.comboAdministrador.getSelectedItem().equals(Constantes.ZAPATERO_ROL)) {
            System.out.println(this.comboAdministrador.getSelectedItem());
        }
        if (this.comboAdministrador.getSelectedItem().equals(Constantes.ADMIN_ROL)) {
            System.out.println(this.comboAdministrador.getSelectedItem());
        }
        
    }//GEN-LAST:event_cambiarRolActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        LoginGUI login = new LoginGUI();
        login.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void comboAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAdministradorActionPerformed
        if ( Constantes.ADMIN_EMPTY.equals(this.comboAdministrador.getSelectedItem()) )
            return;
        
        if ( Constantes.ADMIN_PERSONA.equals(this.comboAdministrador.getSelectedItem()) ) {
            AdminPersonaGUI adminPersona = new AdminPersonaGUI();
            adminPersona.setVisible(Boolean.TRUE);
            this.dispose();
        }
        
        if (Constantes.ADMIN_ADMINISTRAR.equals(this.comboAdministrador.getSelectedItem())) {
            AdminReparacionGUI admin = new AdminReparacionGUI();
            admin.setVisible(Boolean.TRUE);
            this.dispose();
        }
        
        if ( Constantes.ADMIN_INSUMO.equals(this.comboAdministrador.getSelectedItem())){
            AdminInsumoGUI adminInsumo = new AdminInsumoGUI();
            adminInsumo.setVisible(Boolean.TRUE);
            this.dispose();
        }
            
    }//GEN-LAST:event_comboAdministradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RolAdministradorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RolAdministradorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RolAdministradorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RolAdministradorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RolAdministradorGUI().setVisible(true);
            }
        });
    }
   
    /**
     * metodo el cual agrega items al combo
     */
    public void addComboAdmin() {
        this.comboAdministrador.addItem(Constantes.ADMIN_EMPTY);
        this.comboAdministrador.addItem(Constantes.ADMIN_PERSONA);
        this.comboAdministrador.addItem(Constantes.ADMIN_INSUMO);
        this.comboAdministrador.addItem(Constantes.ADMIN_ADMINISTRAR);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiarRol;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JComboBox<String> comboAdministrador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
